// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZOmV7fUE7Hcw4mEio5rjyo2dtzrl_sg0',
    appId: '1:799733583398:web:9bf224772efa984999a0e7',
    messagingSenderId: '799733583398',
    projectId: 'speedy-league-335221',
    authDomain: 'speedy-league-335221.firebaseapp.com',
    databaseURL: 'https://speedy-league-335221-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speedy-league-335221.appspot.com',
    measurementId: 'G-WWB0TSPC99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjxwhCaDfUcbJbIaQN2JpsIO-kait5fw',
    appId: '1:799733583398:android:f0e656cab806296399a0e7',
    messagingSenderId: '799733583398',
    projectId: 'speedy-league-335221',
    databaseURL: 'https://speedy-league-335221-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speedy-league-335221.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBWPTNdUfqhOeURANtBaPYdQ_R9GnI88',
    appId: '1:799733583398:ios:6b9f3bb4808764cf99a0e7',
    messagingSenderId: '799733583398',
    projectId: 'speedy-league-335221',
    databaseURL: 'https://speedy-league-335221-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speedy-league-335221.appspot.com',
    androidClientId: '799733583398-5cnhrks4otsrec5d6gvd9ovhigsmo905.apps.googleusercontent.com',
    iosClientId: '799733583398-m7hrgumed9rh08fe6jih1m9mj37nm9lo.apps.googleusercontent.com',
    iosBundleId: 'com.ibaismedia.ibaismedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiBWPTNdUfqhOeURANtBaPYdQ_R9GnI88',
    appId: '1:799733583398:ios:dbd985bfbfa7bcf399a0e7',
    messagingSenderId: '799733583398',
    projectId: 'speedy-league-335221',
    databaseURL: 'https://speedy-league-335221-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'speedy-league-335221.appspot.com',
    androidClientId: '799733583398-5cnhrks4otsrec5d6gvd9ovhigsmo905.apps.googleusercontent.com',
    iosClientId: '799733583398-icd76u0d8c5kk03dg7ppe7ff8d8mfhc1.apps.googleusercontent.com',
    iosBundleId: 'com.ibaismedia.ibaismedia.RunnerTests',
  );
}
